### ISSUE TITLE
[EPIC1] Alpha Version 사용자가 코드 리뷰를 신청할 수 있는 웹사이트

### ISSUE THREAD

**Issue by srngch** [42ruth/co-review#1]
- 사용자: 팀원
- 기능에 초점을 맞춘 alpha version

## Dev

- Dev1: REST API 구축하기
    - [x] #12
    - [x] #10
    - [x] #11
    - [x] #30
    - 포스트 목록 가져오기 GET `/posts`
    - 포스트 가져오기 GET `/posts/:number`
    - 포스트 등록하기 POST `posts`
    - 포스트 삭제하기 DELETE `posts`
- Dev2: `yarn dev` 환경 설정
    - [x] 버전 맞추기
    - [x] prettier, eslint
    - [x] file structure
    - [x] router 
    - [x] issue & PR template
    - [x] 커밋 커미션 정하기 
    - [x] #13
- Dev3: 웹사이트 기본 틀 구축하기
    - [x] #8
- Dev4: 프론트엔드에서 REST API 호출하기
    - [x] #19
      - `axios`? `fetch`?
      -  [x] #38
- Dev5: ts 타입 정의
    - 타입 정의가 포함된 커밋은 PR `리뷰어에게`에 명시하기
- Dev6: 개발 브랜치 생성
    - [x] #14

## 유저 스토리

- 스토리1: 사용자는 글쓰기 버튼을 눌러서 포스트(코드리뷰 신청 내용)를 작성할 수 있다
    - [x] #18
        - router로 리액트 앱에서 이동
    - [x] #9
       - Form 페이지
       - 메인 페이지
    - [x] #41
    - [x] #27
       - Regex URL 유효성 검사
    - [x] #28
       - XSS 처리 -> EPIC2로 이동
       - 최소 0자, 최대 300자 글자수 체크
    - [x] #39
- 스토리2: 사용자는 메인 페이지에서 포스트 목록을 확인할 수 있다
    - [x] #25
    - [x] #16
          - 이름, 아이디는 일단 더미 테스트
          - 날짜는 상대 날짜는 최대 6일 전, 그 이후로는 절대 날짜
- 스토리3: 사용자는 포스트 목록에서 포스트를 눌러서 PR 페이지로 이동할 수 있다
    - [x] #45
        - 외부 사이트로 이동 
        - 태그 고민 a or button

-> 총 31시간 + @
- 5명 * 4시간 * 2일

---

- [x] #55

---

- Form 페이지에 들어갈 '리뷰 신청하기' 가이드 내용 작성하기
- 메인 페이지 - 무한 스크롤 구현하기[4h+@]
- [ ]  포스트 목록 가져오기 GET `/posts`
        - params: 개수, 범위
           - `limits=10&page=2`

---

## 추가 Task
- [x] API 문서를 서버에 맞춰서 업데이트
- [x] API 객체 키에 맞춰서 ts interface 수정하기
- [x] #57
- [x] #58 
- [x] #60
  - main과 develop 브랜치를 따로 배포할 수 있는 방법 찾아보기
- [x] #61
